let Descriptif_forfait = 
[
  {
   "jour": 1,
   "titre": "départ",
   "contenu": "Départ de Montréal pour la Corse, «L’île aux trésors ». Vol sur Air Transat. Repas puis petit déjeuner à bord.",
   "photo": "./public/images/bastia.jpg"
 },
 {
  "jour": 2,
  "titre": "arrivée à Figari",
  "contenu": "Arrivée à l’aéroport de Marseille où votre guide corse vous attendra. Récupération des  bagages. Repas de midi au restaurant Chefs en Provence. Puis vol de correspondance de 45 minutes sur Air Corsica, pour l'aéroport de Figari situé à quinze minutes de Bonifaziu (Bonifacio). Installation à votre hôtel. Souper libre (d’excellents restaurants se trouvent à quelques pas de l’hôtel, sur le port de plaisance, qui est un véritable petit fjord).",
  "photo": "./public/images/Arbre_Corse_GR20.jpg"
 },
 {
  "jour": 3,
  "titre": "Visite de Bonifaziu",
  "contenu": "<p>Visite de Bonifaziu (Bonifacio), la ville extrême, où l’on a rendez-vous avec l’extrême beauté. Belle, mais plus encore étonnante, Bonifaziu est  une ville à part, « une île dans l’île »,  disent les Corses. Tout y est différent : nature, parler, couleurs ; Bonifaziu n’a qu’une chose en commun avec le reste de la Corse : la beauté.  Défiant les lois de l’équilibre, perchée sur de hautes falaises de calcaire blanc, ceinturée de remparts et de bastions qui rappellent son histoire mouvementée, la «ville funambule» a toujours fortement subjugué ses visiteurs. Elle est également chargée d’histoire et vit passer bien des hommes célèbres tels que, Ulysse, Saint François d’Assise, Charles Quint, Bonaparte et «la plus vieille dame de Corse» (âgée de 8.750 ans).</p> <p> Après une mini-croisière incluse d’1h15 environ (grotte Napoléon, «tapis d’orient », la calanque, le gouvernail de la Corse, le grain de sable…), vous  monterez dans la haute ville abritée derrière des remparts monumentaux. Là vous visiterez la vieille cité et ses ruelles étroites, ses arc-boutants, son belvédère impressionnant, l’église Ste Marie Majeure et le Bastion du Mémorial avec ses salles souterraines.  Et, pendant votre temps libre, vous ferez des achats dans les nombreuses boutiques d’artisans dont une où vous trouverez la spécialité locale : des produits faits en liège (jupes, gilets, soutien-gorge, vaisselle et objets divers). Pour les plus courageux, il y aura aussi la possibilité de descendre «L’escalier du roi d’Aragon»: 187 marches taillées dans la falaise. Nuit à Bonifaziu. Souper inclus. (0 Kms)</p>",
  "photo": "./public/images/bastia.jpg"
 },
 {
  "jour": 4,
  "titre": "Visite de Bonifaziu",
  "contenu": "<p>Visite de Bonifaziu (Bonifacio), la ville extrême, où l’on a rendez-vous avec l’extrême beauté. Belle, mais plus encore étonnante, Bonifaziu est  une ville à part, « une île dans l’île »,  disent les Corses. Tout y est différent : nature, parler, couleurs ; Bonifaziu n’a qu’une chose en commun avec le reste de la Corse : la beauté.  Défiant les lois de l’équilibre, perchée sur de hautes falaises de calcaire blanc, ceinturée de remparts et de bastions qui rappellent son histoire mouvementée, la «ville funambule» a toujours fortement subjugué ses visiteurs. Elle est également chargée d’histoire et vit passer bien des hommes célèbres tels que, Ulysse, Saint François d’Assise, Charles Quint, Bonaparte et «la plus vieille dame de Corse» (âgée de 8.750 ans).</p> <p> Après une mini-croisière incluse d’1h15 environ (grotte Napoléon, «tapis d’orient », la calanque, le gouvernail de la Corse, le grain de sable…), vous  monterez dans la haute ville abritée derrière des remparts monumentaux. Là vous visiterez la vieille cité et ses ruelles étroites, ses arc-boutants, son belvédère impressionnant, l’église Ste Marie Majeure et le Bastion du Mémorial avec ses salles souterraines.  Et, pendant votre temps libre, vous ferez des achats dans les nombreuses boutiques d’artisans dont une où vous trouverez la spécialité locale : des produits faits en liège (jupes, gilets, soutien-gorge, vaisselle et objets divers). Pour les plus courageux, il y aura aussi la possibilité de descendre «L’escalier du roi d’Aragon»: 187 marches taillées dans la falaise. Nuit à Bonifaziu. Souper inclus. (0 Kms)</p>",
  "photo": "./public/images/bastia.jpg"
 },
 {
  "jour": 5,
  "titre": "Visite de Bonifaziu",
  "contenu": "<p>Visite de Bonifaziu (Bonifacio), la ville extrême, où l’on a rendez-vous avec l’extrême beauté. Belle, mais plus encore étonnante, Bonifaziu est  une ville à part, « une île dans l’île »,  disent les Corses. Tout y est différent : nature, parler, couleurs ; Bonifaziu n’a qu’une chose en commun avec le reste de la Corse : la beauté.  Défiant les lois de l’équilibre, perchée sur de hautes falaises de calcaire blanc, ceinturée de remparts et de bastions qui rappellent son histoire mouvementée, la «ville funambule» a toujours fortement subjugué ses visiteurs. Elle est également chargée d’histoire et vit passer bien des hommes célèbres tels que, Ulysse, Saint François d’Assise, Charles Quint, Bonaparte et «la plus vieille dame de Corse» (âgée de 8.750 ans).</p> <p> Après une mini-croisière incluse d’1h15 environ (grotte Napoléon, «tapis d’orient », la calanque, le gouvernail de la Corse, le grain de sable…), vous  monterez dans la haute ville abritée derrière des remparts monumentaux. Là vous visiterez la vieille cité et ses ruelles étroites, ses arc-boutants, son belvédère impressionnant, l’église Ste Marie Majeure et le Bastion du Mémorial avec ses salles souterraines.  Et, pendant votre temps libre, vous ferez des achats dans les nombreuses boutiques d’artisans dont une où vous trouverez la spécialité locale : des produits faits en liège (jupes, gilets, soutien-gorge, vaisselle et objets divers). Pour les plus courageux, il y aura aussi la possibilité de descendre «L’escalier du roi d’Aragon»: 187 marches taillées dans la falaise. Nuit à Bonifaziu. Souper inclus. (0 Kms)</p>",
  "photo": "./public/images/bastia.jpg"
 },
 {
  "jour": 6,
  "titre": "Visite de Bonifaziu",
  "contenu": "<p>Visite de Bonifaziu (Bonifacio), la ville extrême, où l’on a rendez-vous avec l’extrême beauté. Belle, mais plus encore étonnante, Bonifaziu est  une ville à part, « une île dans l’île »,  disent les Corses. Tout y est différent : nature, parler, couleurs ; Bonifaziu n’a qu’une chose en commun avec le reste de la Corse : la beauté.  Défiant les lois de l’équilibre, perchée sur de hautes falaises de calcaire blanc, ceinturée de remparts et de bastions qui rappellent son histoire mouvementée, la «ville funambule» a toujours fortement subjugué ses visiteurs. Elle est également chargée d’histoire et vit passer bien des hommes célèbres tels que, Ulysse, Saint François d’Assise, Charles Quint, Bonaparte et «la plus vieille dame de Corse» (âgée de 8.750 ans).</p> <p> Après une mini-croisière incluse d’1h15 environ (grotte Napoléon, «tapis d’orient », la calanque, le gouvernail de la Corse, le grain de sable…), vous  monterez dans la haute ville abritée derrière des remparts monumentaux. Là vous visiterez la vieille cité et ses ruelles étroites, ses arc-boutants, son belvédère impressionnant, l’église Ste Marie Majeure et le Bastion du Mémorial avec ses salles souterraines.  Et, pendant votre temps libre, vous ferez des achats dans les nombreuses boutiques d’artisans dont une où vous trouverez la spécialité locale : des produits faits en liège (jupes, gilets, soutien-gorge, vaisselle et objets divers). Pour les plus courageux, il y aura aussi la possibilité de descendre «L’escalier du roi d’Aragon»: 187 marches taillées dans la falaise. Nuit à Bonifaziu. Souper inclus. (0 Kms)</p>",
  "photo": "./public/images/bastia.jpg"
 },
 {
  "jour": 7,
  "titre": "Visite de Bonifaziu",
  "contenu": "<p>Visite de Bonifaziu (Bonifacio), la ville extrême, où l’on a rendez-vous avec l’extrême beauté. Belle, mais plus encore étonnante, Bonifaziu est  une ville à part, « une île dans l’île »,  disent les Corses. Tout y est différent : nature, parler, couleurs ; Bonifaziu n’a qu’une chose en commun avec le reste de la Corse : la beauté.  Défiant les lois de l’équilibre, perchée sur de hautes falaises de calcaire blanc, ceinturée de remparts et de bastions qui rappellent son histoire mouvementée, la «ville funambule» a toujours fortement subjugué ses visiteurs. Elle est également chargée d’histoire et vit passer bien des hommes célèbres tels que, Ulysse, Saint François d’Assise, Charles Quint, Bonaparte et «la plus vieille dame de Corse» (âgée de 8.750 ans).</p> <p> Après une mini-croisière incluse d’1h15 environ (grotte Napoléon, «tapis d’orient », la calanque, le gouvernail de la Corse, le grain de sable…), vous  monterez dans la haute ville abritée derrière des remparts monumentaux. Là vous visiterez la vieille cité et ses ruelles étroites, ses arc-boutants, son belvédère impressionnant, l’église Ste Marie Majeure et le Bastion du Mémorial avec ses salles souterraines.  Et, pendant votre temps libre, vous ferez des achats dans les nombreuses boutiques d’artisans dont une où vous trouverez la spécialité locale : des produits faits en liège (jupes, gilets, soutien-gorge, vaisselle et objets divers). Pour les plus courageux, il y aura aussi la possibilité de descendre «L’escalier du roi d’Aragon»: 187 marches taillées dans la falaise. Nuit à Bonifaziu. Souper inclus. (0 Kms)</p>",
  "photo": "./public/images/bastia.jpg"
 },
 {
  "jour": 8,
  "titre": "Visite de Bonifaziu",
  "contenu": "<p>Visite de Bonifaziu (Bonifacio), la ville extrême, où l’on a rendez-vous avec l’extrême beauté. Belle, mais plus encore étonnante, Bonifaziu est  une ville à part, « une île dans l’île »,  disent les Corses. Tout y est différent : nature, parler, couleurs ; Bonifaziu n’a qu’une chose en commun avec le reste de la Corse : la beauté.  Défiant les lois de l’équilibre, perchée sur de hautes falaises de calcaire blanc, ceinturée de remparts et de bastions qui rappellent son histoire mouvementée, la «ville funambule» a toujours fortement subjugué ses visiteurs. Elle est également chargée d’histoire et vit passer bien des hommes célèbres tels que, Ulysse, Saint François d’Assise, Charles Quint, Bonaparte et «la plus vieille dame de Corse» (âgée de 8.750 ans).</p> <p> Après une mini-croisière incluse d’1h15 environ (grotte Napoléon, «tapis d’orient », la calanque, le gouvernail de la Corse, le grain de sable…), vous  monterez dans la haute ville abritée derrière des remparts monumentaux. Là vous visiterez la vieille cité et ses ruelles étroites, ses arc-boutants, son belvédère impressionnant, l’église Ste Marie Majeure et le Bastion du Mémorial avec ses salles souterraines.  Et, pendant votre temps libre, vous ferez des achats dans les nombreuses boutiques d’artisans dont une où vous trouverez la spécialité locale : des produits faits en liège (jupes, gilets, soutien-gorge, vaisselle et objets divers). Pour les plus courageux, il y aura aussi la possibilité de descendre «L’escalier du roi d’Aragon»: 187 marches taillées dans la falaise. Nuit à Bonifaziu. Souper inclus. (0 Kms)</p>",
  "photo": "./public/images/bastia.jpg"
 },
 {
  "jour": 9,
  "titre": "Visite de Bonifaziu",
  "contenu": "<p>Visite de Bonifaziu (Bonifacio), la ville extrême, où l’on a rendez-vous avec l’extrême beauté. Belle, mais plus encore étonnante, Bonifaziu est  une ville à part, « une île dans l’île »,  disent les Corses. Tout y est différent : nature, parler, couleurs ; Bonifaziu n’a qu’une chose en commun avec le reste de la Corse : la beauté.  Défiant les lois de l’équilibre, perchée sur de hautes falaises de calcaire blanc, ceinturée de remparts et de bastions qui rappellent son histoire mouvementée, la «ville funambule» a toujours fortement subjugué ses visiteurs. Elle est également chargée d’histoire et vit passer bien des hommes célèbres tels que, Ulysse, Saint François d’Assise, Charles Quint, Bonaparte et «la plus vieille dame de Corse» (âgée de 8.750 ans).</p> <p> Après une mini-croisière incluse d’1h15 environ (grotte Napoléon, «tapis d’orient », la calanque, le gouvernail de la Corse, le grain de sable…), vous  monterez dans la haute ville abritée derrière des remparts monumentaux. Là vous visiterez la vieille cité et ses ruelles étroites, ses arc-boutants, son belvédère impressionnant, l’église Ste Marie Majeure et le Bastion du Mémorial avec ses salles souterraines.  Et, pendant votre temps libre, vous ferez des achats dans les nombreuses boutiques d’artisans dont une où vous trouverez la spécialité locale : des produits faits en liège (jupes, gilets, soutien-gorge, vaisselle et objets divers). Pour les plus courageux, il y aura aussi la possibilité de descendre «L’escalier du roi d’Aragon»: 187 marches taillées dans la falaise. Nuit à Bonifaziu. Souper inclus. (0 Kms)</p>",
  "photo": "./public/images/bastia.jpg"
 },
 {
  "jour": 10,
  "titre": "Visite de Bonifaziu",
  "contenu": "<p>Visite de Bonifaziu (Bonifacio), la ville extrême, où l’on a rendez-vous avec l’extrême beauté. Belle, mais plus encore étonnante, Bonifaziu est  une ville à part, « une île dans l’île »,  disent les Corses. Tout y est différent : nature, parler, couleurs ; Bonifaziu n’a qu’une chose en commun avec le reste de la Corse : la beauté.  Défiant les lois de l’équilibre, perchée sur de hautes falaises de calcaire blanc, ceinturée de remparts et de bastions qui rappellent son histoire mouvementée, la «ville funambule» a toujours fortement subjugué ses visiteurs. Elle est également chargée d’histoire et vit passer bien des hommes célèbres tels que, Ulysse, Saint François d’Assise, Charles Quint, Bonaparte et «la plus vieille dame de Corse» (âgée de 8.750 ans).</p> <p> Après une mini-croisière incluse d’1h15 environ (grotte Napoléon, «tapis d’orient », la calanque, le gouvernail de la Corse, le grain de sable…), vous  monterez dans la haute ville abritée derrière des remparts monumentaux. Là vous visiterez la vieille cité et ses ruelles étroites, ses arc-boutants, son belvédère impressionnant, l’église Ste Marie Majeure et le Bastion du Mémorial avec ses salles souterraines.  Et, pendant votre temps libre, vous ferez des achats dans les nombreuses boutiques d’artisans dont une où vous trouverez la spécialité locale : des produits faits en liège (jupes, gilets, soutien-gorge, vaisselle et objets divers). Pour les plus courageux, il y aura aussi la possibilité de descendre «L’escalier du roi d’Aragon»: 187 marches taillées dans la falaise. Nuit à Bonifaziu. Souper inclus. (0 Kms)</p>",
  "photo": "./public/images/bastia.jpg"
 },
 {
  "jour": 11,
  "titre": "Visite de Bonifaziu",
  "contenu": "<p>Visite de Bonifaziu (Bonifacio), la ville extrême, où l’on a rendez-vous avec l’extrême beauté. Belle, mais plus encore étonnante, Bonifaziu est  une ville à part, « une île dans l’île »,  disent les Corses. Tout y est différent : nature, parler, couleurs ; Bonifaziu n’a qu’une chose en commun avec le reste de la Corse : la beauté.  Défiant les lois de l’équilibre, perchée sur de hautes falaises de calcaire blanc, ceinturée de remparts et de bastions qui rappellent son histoire mouvementée, la «ville funambule» a toujours fortement subjugué ses visiteurs. Elle est également chargée d’histoire et vit passer bien des hommes célèbres tels que, Ulysse, Saint François d’Assise, Charles Quint, Bonaparte et «la plus vieille dame de Corse» (âgée de 8.750 ans).</p> <p> Après une mini-croisière incluse d’1h15 environ (grotte Napoléon, «tapis d’orient », la calanque, le gouvernail de la Corse, le grain de sable…), vous  monterez dans la haute ville abritée derrière des remparts monumentaux. Là vous visiterez la vieille cité et ses ruelles étroites, ses arc-boutants, son belvédère impressionnant, l’église Ste Marie Majeure et le Bastion du Mémorial avec ses salles souterraines.  Et, pendant votre temps libre, vous ferez des achats dans les nombreuses boutiques d’artisans dont une où vous trouverez la spécialité locale : des produits faits en liège (jupes, gilets, soutien-gorge, vaisselle et objets divers). Pour les plus courageux, il y aura aussi la possibilité de descendre «L’escalier du roi d’Aragon»: 187 marches taillées dans la falaise. Nuit à Bonifaziu. Souper inclus. (0 Kms)</p>",
  "photo": "./public/images/bastia.jpg"
 },
 {
  "jour": 12,
  "titre": "Visite de Bonifaziu",
  "contenu": "<p>Visite de Bonifaziu (Bonifacio), la ville extrême, où l’on a rendez-vous avec l’extrême beauté. Belle, mais plus encore étonnante, Bonifaziu est  une ville à part, « une île dans l’île »,  disent les Corses. Tout y est différent : nature, parler, couleurs ; Bonifaziu n’a qu’une chose en commun avec le reste de la Corse : la beauté.  Défiant les lois de l’équilibre, perchée sur de hautes falaises de calcaire blanc, ceinturée de remparts et de bastions qui rappellent son histoire mouvementée, la «ville funambule» a toujours fortement subjugué ses visiteurs. Elle est également chargée d’histoire et vit passer bien des hommes célèbres tels que, Ulysse, Saint François d’Assise, Charles Quint, Bonaparte et «la plus vieille dame de Corse» (âgée de 8.750 ans).</p> <p> Après une mini-croisière incluse d’1h15 environ (grotte Napoléon, «tapis d’orient », la calanque, le gouvernail de la Corse, le grain de sable…), vous  monterez dans la haute ville abritée derrière des remparts monumentaux. Là vous visiterez la vieille cité et ses ruelles étroites, ses arc-boutants, son belvédère impressionnant, l’église Ste Marie Majeure et le Bastion du Mémorial avec ses salles souterraines.  Et, pendant votre temps libre, vous ferez des achats dans les nombreuses boutiques d’artisans dont une où vous trouverez la spécialité locale : des produits faits en liège (jupes, gilets, soutien-gorge, vaisselle et objets divers). Pour les plus courageux, il y aura aussi la possibilité de descendre «L’escalier du roi d’Aragon»: 187 marches taillées dans la falaise. Nuit à Bonifaziu. Souper inclus. (0 Kms)</p>",
  "photo": "./public/images/bastia.jpg"
 },
 {
  "jour": 13,
  "titre": "Visite de Bonifaziu",
  "contenu": "<p>Visite de Bonifaziu (Bonifacio), la ville extrême, où l’on a rendez-vous avec l’extrême beauté. Belle, mais plus encore étonnante, Bonifaziu est  une ville à part, « une île dans l’île »,  disent les Corses. Tout y est différent : nature, parler, couleurs ; Bonifaziu n’a qu’une chose en commun avec le reste de la Corse : la beauté.  Défiant les lois de l’équilibre, perchée sur de hautes falaises de calcaire blanc, ceinturée de remparts et de bastions qui rappellent son histoire mouvementée, la «ville funambule» a toujours fortement subjugué ses visiteurs. Elle est également chargée d’histoire et vit passer bien des hommes célèbres tels que, Ulysse, Saint François d’Assise, Charles Quint, Bonaparte et «la plus vieille dame de Corse» (âgée de 8.750 ans).</p> <p> Après une mini-croisière incluse d’1h15 environ (grotte Napoléon, «tapis d’orient », la calanque, le gouvernail de la Corse, le grain de sable…), vous  monterez dans la haute ville abritée derrière des remparts monumentaux. Là vous visiterez la vieille cité et ses ruelles étroites, ses arc-boutants, son belvédère impressionnant, l’église Ste Marie Majeure et le Bastion du Mémorial avec ses salles souterraines.  Et, pendant votre temps libre, vous ferez des achats dans les nombreuses boutiques d’artisans dont une où vous trouverez la spécialité locale : des produits faits en liège (jupes, gilets, soutien-gorge, vaisselle et objets divers). Pour les plus courageux, il y aura aussi la possibilité de descendre «L’escalier du roi d’Aragon»: 187 marches taillées dans la falaise. Nuit à Bonifaziu. Souper inclus. (0 Kms)</p>",
  "photo": "./public/images/bastia.jpg"
 },
 {
  "jour": 14,
  "titre": "Visite de Bonifaziu",
  "contenu": "<p>Visite de Bonifaziu (Bonifacio), la ville extrême, où l’on a rendez-vous avec l’extrême beauté. Belle, mais plus encore étonnante, Bonifaziu est  une ville à part, « une île dans l’île »,  disent les Corses. Tout y est différent : nature, parler, couleurs ; Bonifaziu n’a qu’une chose en commun avec le reste de la Corse : la beauté.  Défiant les lois de l’équilibre, perchée sur de hautes falaises de calcaire blanc, ceinturée de remparts et de bastions qui rappellent son histoire mouvementée, la «ville funambule» a toujours fortement subjugué ses visiteurs. Elle est également chargée d’histoire et vit passer bien des hommes célèbres tels que, Ulysse, Saint François d’Assise, Charles Quint, Bonaparte et «la plus vieille dame de Corse» (âgée de 8.750 ans).</p> <p> Après une mini-croisière incluse d’1h15 environ (grotte Napoléon, «tapis d’orient », la calanque, le gouvernail de la Corse, le grain de sable…), vous  monterez dans la haute ville abritée derrière des remparts monumentaux. Là vous visiterez la vieille cité et ses ruelles étroites, ses arc-boutants, son belvédère impressionnant, l’église Ste Marie Majeure et le Bastion du Mémorial avec ses salles souterraines.  Et, pendant votre temps libre, vous ferez des achats dans les nombreuses boutiques d’artisans dont une où vous trouverez la spécialité locale : des produits faits en liège (jupes, gilets, soutien-gorge, vaisselle et objets divers). Pour les plus courageux, il y aura aussi la possibilité de descendre «L’escalier du roi d’Aragon»: 187 marches taillées dans la falaise. Nuit à Bonifaziu. Souper inclus. (0 Kms)</p>",
  "photo": "./public/images/bastia.jpg"
 },
 {
  "jour": 15,
  "titre": "Visite de Bonifaziu",
  "contenu": "<p>Visite de Bonifaziu (Bonifacio), la ville extrême, où l’on a rendez-vous avec l’extrême beauté. Belle, mais plus encore étonnante, Bonifaziu est  une ville à part, « une île dans l’île »,  disent les Corses. Tout y est différent : nature, parler, couleurs ; Bonifaziu n’a qu’une chose en commun avec le reste de la Corse : la beauté.  Défiant les lois de l’équilibre, perchée sur de hautes falaises de calcaire blanc, ceinturée de remparts et de bastions qui rappellent son histoire mouvementée, la «ville funambule» a toujours fortement subjugué ses visiteurs. Elle est également chargée d’histoire et vit passer bien des hommes célèbres tels que, Ulysse, Saint François d’Assise, Charles Quint, Bonaparte et «la plus vieille dame de Corse» (âgée de 8.750 ans).</p> <p> Après une mini-croisière incluse d’1h15 environ (grotte Napoléon, «tapis d’orient », la calanque, le gouvernail de la Corse, le grain de sable…), vous  monterez dans la haute ville abritée derrière des remparts monumentaux. Là vous visiterez la vieille cité et ses ruelles étroites, ses arc-boutants, son belvédère impressionnant, l’église Ste Marie Majeure et le Bastion du Mémorial avec ses salles souterraines.  Et, pendant votre temps libre, vous ferez des achats dans les nombreuses boutiques d’artisans dont une où vous trouverez la spécialité locale : des produits faits en liège (jupes, gilets, soutien-gorge, vaisselle et objets divers). Pour les plus courageux, il y aura aussi la possibilité de descendre «L’escalier du roi d’Aragon»: 187 marches taillées dans la falaise. Nuit à Bonifaziu. Souper inclus. (0 Kms)</p>",
  "photo": "./public/images/bastia.jpg"
 },
 {
  "jour": 16,
  "titre": "Visite de Bonifaziu",
  "contenu": "<p>Visite de Bonifaziu (Bonifacio), la ville extrême, où l’on a rendez-vous avec l’extrême beauté. Belle, mais plus encore étonnante, Bonifaziu est  une ville à part, « une île dans l’île »,  disent les Corses. Tout y est différent : nature, parler, couleurs ; Bonifaziu n’a qu’une chose en commun avec le reste de la Corse : la beauté.  Défiant les lois de l’équilibre, perchée sur de hautes falaises de calcaire blanc, ceinturée de remparts et de bastions qui rappellent son histoire mouvementée, la «ville funambule» a toujours fortement subjugué ses visiteurs. Elle est également chargée d’histoire et vit passer bien des hommes célèbres tels que, Ulysse, Saint François d’Assise, Charles Quint, Bonaparte et «la plus vieille dame de Corse» (âgée de 8.750 ans).</p> <p> Après une mini-croisière incluse d’1h15 environ (grotte Napoléon, «tapis d’orient », la calanque, le gouvernail de la Corse, le grain de sable…), vous  monterez dans la haute ville abritée derrière des remparts monumentaux. Là vous visiterez la vieille cité et ses ruelles étroites, ses arc-boutants, son belvédère impressionnant, l’église Ste Marie Majeure et le Bastion du Mémorial avec ses salles souterraines.  Et, pendant votre temps libre, vous ferez des achats dans les nombreuses boutiques d’artisans dont une où vous trouverez la spécialité locale : des produits faits en liège (jupes, gilets, soutien-gorge, vaisselle et objets divers). Pour les plus courageux, il y aura aussi la possibilité de descendre «L’escalier du roi d’Aragon»: 187 marches taillées dans la falaise. Nuit à Bonifaziu. Souper inclus. (0 Kms)</p>",
  "photo": "./public/images/bastia.jpg"
 }
]
